### PR TITLE
ignoring projects files

### PR DESCRIPTION
**Pull request by fchauveau**
Hi, I've just update git ignore file to add all android studio files (_.iml, .idea/_) that don't need to be committed
- I also remove from git all those files

### CODE REVIEW

**Comment by galadril** [comment]
Thanks!

**Comment by RoadXY** [comment]
I hope this works.
Have been trying to figure this out because I have to manually disable these files every pull request :-/

**Comment by RoadXY** [comment]
Confirmed!
Pushed to my AVD, re-synced Gradle and still no new files when pushing the commit button!
/Me happy person!

**Comment by galadril** [comment]
Nice 1

**Comment by fchauveau** [comment]
Yep, once commited to remove files from git you should use `git rm --cached`
If you still have troubles, you can drop local folder and do a new git clone.

**Comment by RoadXY** [comment]
Great, thanks.

**Pull request merged**
