### PR TITLE
Small correct color button

### PR DESCRIPTION
**Pull request by ghost**
Now is ideal

### CODE REVIEW

**Comment by galadril** [comment]
I've changed the colors already to grey.. 
I like that way more, sorry

https://github.com/galadril/DomoticzForAndroid/commit/87d6da21d7dc172f475337908e6e34846d9c0036

**Comment by ghost** [comment]
But on/ off is not grey. Maybe active button better should be green

**Comment by galadril** [comment]
on/off switch is grey (when turned off).
Thats the color I use now.

Sorry to say, but we have more urgent matters to work on.

**Comment by ghost** [comment]
But i see you color now and in my opinion is to bright. Is not see  that is button. I think that should be darknes.

**Comment by galadril** [comment]
That's probably then just a matter of tast..

**Comment by ghost** [comment]
But maybe better is green material_teal_500 ? It is the same as switch on/off (when is on). Button log, timer is also as ON and should be the same color.

But can you move button log, timer etc to set in one line with text last seen ? I show on forum what i mean.

**Pull request closed without merging**
