### PR TITLE
Copyright, lint errors

### PR DESCRIPTION
**Pull request by RoadXY**
Copyright info in all files
Removed several lint errors, unused imports

### CODE REVIEW

**Comment by galadril** [comment]
mmm...
This branch has conflicts that must be resolved

**Comment by galadril** [comment]
Can you merge/update this branch from the master??

**Comment by RoadXY** [comment]
I saw when I made the pull request but there was a message I could still create the pull request.
No, I can't update ether because I had this one ready.

Then I must redo 193 files :-(

**Comment by RoadXY** [comment]
What are the options for conflict resolvement?

I'm sure on other project these issues would come up.

**Comment by RoadXY** [comment]
Maybe ignore the files you've changed and I'll redo these?

**Comment by RoadXY** [comment]
Great!
Do you know if I have to redo files?

**Comment by galadril** [comment]
It was quite some work...
But I think everything is in now..

**Comment by RoadXY** [comment]
Great.
Maybe we have to update each other somehow when we're working on something?

**Pull request merged**
