### PR TITLE
Geolocation - address implementation (part deux)

### PR DESCRIPTION
**Pull request by RoadXY**

### CODE REVIEW

**Comment by RoadXY** [comment]
@galadril please tell me your opinion on Geolocation and all other changes/updates :-D

**Comment by galadril** [comment]
Looks great (still checking at the moment)

**Comment by RoadXY** [comment]
Ok

**Comment by galadril** [comment]
You've been doing quite some code cleaning ;) nice

**Comment by RoadXY** [comment]
Did you find any issues? Been running and testing as much as I could.

**Comment by galadril** [comment]
No, could not find any problems, so good job!

**Pull request merged**
